version: "3.9"
services:
  minio:
    image: docker.io/bitnami/minio:2021
    ports:
      - 9000:9000
    volumes:
      - './minio_data:/data'
    environment:
      MINIO_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
      MINIO_SECRET_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  poloniex_socket:
    image: "poloniex_socket:0.0.1"
    environment:
      MINIO_SERVER_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
      MINIO_SERVER_SECRET_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      PYTHONUNBUFFERED: 1
    ports:
      - 9001:9001
  poloniex_enrich:
    image: "poloniex_enrich:0.0.1"
    environment:
      MINIO_SERVER_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
      MINIO_SERVER_SECRET_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      PYTHONUNBUFFERED: 1
    ports:
      - 9002:9002
